### ISSUE TITLE
pip install error downloading new versions

### ISSUE THREAD

**Issue by nwalsh1995** [osrsbox/osrsbox-db#85]
Only recently needed to update osrsbox and from that I got some errors when pip installing:

```
Collecting osrsbox (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/47/60/5ca77289b159f7eef12d0f76e492e729fc3f030499d584aa8ddcd30940ae/osrsbox-1.0.4.tar.gz (691kB)
    100% |████████████████████████████████| 696kB 23.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2bza7sx3/osrsbox/setup.py", line 26, in <module>
        with io.open(os.path.join(readme_location, 'README.md'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-2bza7sx3/osrsbox/osrsbox/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2bza7sx3/osrsbox/
```
It seems like the README.md is not being packaged for the upload.

**Comment by osrsbox** [comment]
@nwalsh1995 Thank you for reporting this issue. I changed the package `README.md` file to the file in the `osrsbox` package folder, and messed up the `MANIFEST.md` file. I just pushed the fix and bumped the version to `1.0.5`. Should be working again now.

Many thanks for reporting this. Nothing worse than a package that doesn't install correctly 👎
